In [3]:
import pandas as pd
data=pd.read_csv("hire.csv")
data

,Percentage,Backlog,Internship,First_Round,Communication_Skills,Hired,Unnamed: 6
0,81.00,0,1,75.00,80.00,1,NaN
1,70.00,0,3,87.00,70.00,1,NaN
2,81.00,2,3,75.00,67.00,0,NaN
3,56.00,3,3,42.00,76.00,0,NaN
4,74.00,4,3,82.00,75.00,1,NaN
5,69.00,0,2,74.00,71.00,1,NaN
6,46.00,3,1,67.00,86.00,0,NaN
7,70.00,0,1,78.00,75.00,1,NaN
8,85.00,1,1,65.00,72.00,1,NaN
9,70.00,1,1,80.00,85.00,1,NaN
10,90.00,0,1,88.00,89.00,1,NaN
11,70.00,0,1,84.00,75.00,1,NaN
12,69.00,0,1,66.00,71.00,1,NaN
13,70.00,2,0,85.00,73.00,1,NaN
14,70.00,0,1,67.00,73.00,1,NaN
15,67.00,1,1,64.00,75.00,1,NaN
16,80.00,0,1,68.00,77.00,1,NaN
17,67.00,0,1,66.00,78.00,1,NaN
18,89.00,0,1,78.00,80.00,1,NaN
19,90.00,0,1,90.00,89.00,1,NaN
20,87.00,0,1,88.00,85.00,1,NaN
21,68.00,0,1,80.00,97.00,1,NaN
22,69.00,0,1,78.00,80.00,1,NaN
23,80.00,0,1,84.00,80.00,1,NaN
24,80.00,1,1,76.00,80.00,1,NaN
25,80.00,1,1,88.00,84.00,1,NaN
26,87.00,0,1,85.00,85.00,1,NaN
27,75.00,0,2,80.00,90.00,1,NaN
28,90.00,0,3,70.00,75.00,1,NaN
29,88.00,0,3,85.00,92.00,1,NaN
...,...,...,...,...,...,...,...
347,71.00,4,4,81.00,71.00,1,NaN
348,64.00,1,69,0.00,64.00,1,NaN
349,60.00,3,65,0.00,61.00,1,NaN
350,60.00,6,0,60.00,60.00,0,NaN
351,61.00,6,0,60.00,60.00,0,NaN
352,62.00,5,0,62.00,63.00,0,NaN
353,63.00,4,0,63.00,65.00,0,NaN
354,64.00,3,0,65.00,69.00,0,NaN
355,64.00,5,2,79.00,69.00,0,NaN
356,63.00,6,2,78.00,68.00,0,NaN
357,62.00,7,1,77.00,67.00,0,NaN
358,61.00,8,1,76.00,66.00,0,NaN
359,60.00,9,2,75.00,65.00,0,NaN
360,59.00,8,2,75.00,65.00,0,NaN
361,62.55,1,2,72.00,79.00,1,NaN
362,72.87,0,3,80.30,85.50,1,NaN
363,75.90,0,4,80.00,85.00,1,NaN
364,59.00,4,2,71.00,69.00,0,NaN
365,82.50,3,4,87.00,83.00,1,NaN
366,59.37,3,1,65.00,71.00,0,NaN
367,71.60,0,4,75.00,85.00,1,NaN
368,65.58,2,4,71.00,89.00,1,NaN
369,67.78,5,0,60.00,71.00,0,NaN
370,59.98,5,5,87.00,91.00,1,NaN
371,63.45,5,0,67.00,70.00,0,NaN
372,68.87,2,0,66.67,69.69,0,NaN
373,80.48,0,3,79.00,88.89,1,NaN
374,65.00,2,1,60.00,70.00,1,NaN
375,100.00,5,3,88.00,88.00,1,NaN
376,100.00,8,1,88.00,88.00,0,NaN

In [4]:
#now here we have index number here ranging from 0 to 376 and if we want to sort the index numbers then
data.sort_index(ascending=False)#here we sort in descending order

,Percentage,Backlog,Internship,First_Round,Communication_Skills,Hired,Unnamed: 6
376,100.00,8,1,88.00,88.00,0,NaN
375,100.00,5,3,88.00,88.00,1,NaN
374,65.00,2,1,60.00,70.00,1,NaN
373,80.48,0,3,79.00,88.89,1,NaN
372,68.87,2,0,66.67,69.69,0,NaN
371,63.45,5,0,67.00,70.00,0,NaN
370,59.98,5,5,87.00,91.00,1,NaN
369,67.78,5,0,60.00,71.00,0,NaN
368,65.58,2,4,71.00,89.00,1,NaN
367,71.60,0,4,75.00,85.00,1,NaN
366,59.37,3,1,65.00,71.00,0,NaN
365,82.50,3,4,87.00,83.00,1,NaN
364,59.00,4,2,71.00,69.00,0,NaN
363,75.90,0,4,80.00,85.00,1,NaN
362,72.87,0,3,80.30,85.50,1,NaN
361,62.55,1,2,72.00,79.00,1,NaN
360,59.00,8,2,75.00,65.00,0,NaN
359,60.00,9,2,75.00,65.00,0,NaN
358,61.00,8,1,76.00,66.00,0,NaN
357,62.00,7,1,77.00,67.00,0,NaN
356,63.00,6,2,78.00,68.00,0,NaN
355,64.00,5,2,79.00,69.00,0,NaN
354,64.00,3,0,65.00,69.00,0,NaN
353,63.00,4,0,63.00,65.00,0,NaN
352,62.00,5,0,62.00,63.00,0,NaN
351,61.00,6,0,60.00,60.00,0,NaN
350,60.00,6,0,60.00,60.00,0,NaN
349,60.00,3,65,0.00,61.00,1,NaN
348,64.00,1,69,0.00,64.00,1,NaN
347,71.00,4,4,81.00,71.00,1,NaN
...,...,...,...,...,...,...,...
29,88.00,0,3,85.00,92.00,1,NaN
28,90.00,0,3,70.00,75.00,1,NaN
27,75.00,0,2,80.00,90.00,1,NaN
26,87.00,0,1,85.00,85.00,1,NaN
25,80.00,1,1,88.00,84.00,1,NaN
24,80.00,1,1,76.00,80.00,1,NaN
23,80.00,0,1,84.00,80.00,1,NaN
22,69.00,0,1,78.00,80.00,1,NaN
21,68.00,0,1,80.00,97.00,1,NaN
20,87.00,0,1,88.00,85.00,1,NaN
19,90.00,0,1,90.00,89.00,1,NaN
18,89.00,0,1,78.00,80.00,1,NaN
17,67.00,0,1,66.00,78.00,1,NaN
16,80.00,0,1,68.00,77.00,1,NaN
15,67.00,1,1,64.00,75.00,1,NaN
14,70.00,0,1,67.00,73.00,1,NaN
13,70.00,2,0,85.00,73.00,1,NaN
12,69.00,0,1,66.00,71.00,1,NaN
11,70.00,0,1,84.00,75.00,1,NaN
10,90.00,0,1,88.00,89.00,1,NaN
9,70.00,1,1,80.00,85.00,1,NaN
8,85.00,1,1,65.00,72.00,1,NaN
7,70.00,0,1,78.00,75.00,1,NaN
6,46.00,3,1,67.00,86.00,0,NaN
5,69.00,0,2,74.00,71.00,1,NaN
4,74.00,4,3,82.00,75.00,1,NaN
3,56.00,3,3,42.00,76.00,0,NaN
2,81.00,2,3,75.00,67.00,0,NaN
1,70.00,0,3,87.00,70.00,1,NaN
0,81.00,0,1,75.00,80.00,1,NaN