In [1]:
import pandas as pd
df=pd.read_csv('hire_data1.csv')
df.head(12)

,Percentage,Backlog,Internship,First_Round,Communication_Skills,Hired,Name
0,81.0,0,1,75.0,80.0,1,Canon
1,70.0,0,3,87.0,70.0,1,Ajay
2,81.0,2,3,75.0,67.0,0,Aman
3,56.0,3,3,42.0,76.0,0,Amir
4,74.0,4,3,82.0,75.0,1,Monu
5,69.0,0,2,74.0,71.0,1,Baba
6,46.0,3,1,67.0,86.0,0,Canon
7,70.0,0,1,78.0,75.0,1,Aman
8,85.0,1,1,65.0,72.0,1,Zar
9,70.0,1,1,80.0,85.0,1,Teja
10,90.0,0,1,88.0,89.0,1,Monu
11,70.0,0,1,84.0,75.0,1,Baba

In [2]:
len(df)#shows the number of entries in df

377

In [3]:
df.drop_duplicates(subset=['Percentage'],keep='first')#deletes all the dupliacte values and keeps only the first value

,Percentage,Backlog,Internship,First_Round,Communication_Skills,Hired,Name
0,81.00,0,1,75.00,80.00,1,Canon
1,70.00,0,3,87.00,70.00,1,Ajay
3,56.00,3,3,42.00,76.00,0,Amir
4,74.00,4,3,82.00,75.00,1,Monu
5,69.00,0,2,74.00,71.00,1,Baba
6,46.00,3,1,67.00,86.00,0,Canon
8,85.00,1,1,65.00,72.00,1,Zar
10,90.00,0,1,88.00,89.00,1,Monu
15,67.00,1,1,64.00,75.00,1,Teja
16,80.00,0,1,68.00,77.00,1,Monu
18,89.00,0,1,78.00,80.00,1,Canon
20,87.00,0,1,88.00,85.00,1,Zar
21,68.00,0,1,80.00,97.00,1,Teja
27,75.00,0,2,80.00,90.00,1,Teja
29,88.00,0,3,85.00,92.00,1,Baba
35,77.00,2,3,81.00,77.00,1,Baba
36,60.00,0,1,80.00,80.00,0,Canon
38,76.00,5,1,70.00,72.00,0,Zar
43,55.00,4,1,67.00,75.00,0,Ajay
44,50.00,2,2,55.00,66.00,0,Zar
47,72.00,1,4,70.00,80.00,1,Baba
48,79.00,3,4,85.00,76.00,1,Canon
51,99.00,0,5,90.00,89.00,1,Teja
52,92.00,0,4,89.00,78.00,1,Monu
55,98.00,1,4,80.00,89.00,1,Ajay
59,64.00,0,0,56.00,55.00,0,Baba
62,61.00,4,0,44.00,20.00,0,Zar
63,45.00,1,0,45.00,65.00,0,Teja
66,34.00,9,10,50.00,60.00,0,Canon
68,86.00,1,1,78.00,70.00,1,Zar
...,...,...,...,...,...,...,...
180,71.56,0,2,79.00,75.00,1,Canon
182,69.60,0,2,81.00,85.00,1,Zar
183,69.99,0,1,50.00,10.00,0,Teja
184,68.80,0,3,89.00,91.00,1,Monu
195,98.99,0,6,97.00,100.00,1,Teja
198,84.00,2,4,78.00,89.00,1,Canon
202,59.00,2,2,78.00,81.00,0,Monu
207,47.00,0,2,42.00,46.00,0,Teja
213,90.50,0,2,70.00,85.00,1,Teja
214,68.20,2,1,50.00,60.00,1,Monu
216,68.60,2,1,50.00,60.00,0,Canon
222,52.00,3,4,65.00,65.00,0,Canon
228,66.60,4,2,85.50,90.00,0,Canon
231,69.50,4,4,81.00,80.00,1,Teja
255,71.00,2,1,60.00,77.00,0,Teja
303,33.00,2,0,49.00,70.00,0,Monu
321,79.50,1,2,60.00,71.00,1,Monu
334,41.00,4,5,85.00,62.00,0,Baba
361,62.55,1,2,72.00,79.00,1,Zar
362,72.87,0,3,80.30,85.50,1,Teja
363,75.90,0,4,80.00,85.00,1,Monu
365,82.50,3,4,87.00,83.00,1,Canon
366,59.37,3,1,65.00,71.00,0,Ajay
367,71.60,0,4,75.00,85.00,1,Zar
368,65.58,2,4,71.00,89.00,1,Teja
369,67.78,5,0,60.00,71.00,0,Monu
370,59.98,5,5,87.00,91.00,1,Baba
371,63.45,5,0,67.00,70.00,0,Canon
372,68.87,2,0,66.67,69.69,0,Ajay
373,80.48,0,3,79.00,88.89,1,Zar

In [4]:
len(df.drop_duplicates(subset=['Percentage'],keep='first'))

78

In [5]:
df.drop_duplicates(subset=['Percentage','First_Round'])#this basically concatenates the two columns i.e
#percentage and first round and then drops the duplicate values i.e if percentage and first round in index 1 is 81 and 75
#percentage and first round in index 2  is 81 and 75
#then the row is deleted

,Percentage,Backlog,Internship,First_Round,Communication_Skills,Hired,Name
0,81.00,0,1,75.00,80.00,1,Canon
1,70.00,0,3,87.00,70.00,1,Ajay
3,56.00,3,3,42.00,76.00,0,Amir
4,74.00,4,3,82.00,75.00,1,Monu
5,69.00,0,2,74.00,71.00,1,Baba
6,46.00,3,1,67.00,86.00,0,Canon
7,70.00,0,1,78.00,75.00,1,Aman
8,85.00,1,1,65.00,72.00,1,Zar
9,70.00,1,1,80.00,85.00,1,Teja
10,90.00,0,1,88.00,89.00,1,Monu
11,70.00,0,1,84.00,75.00,1,Baba
12,69.00,0,1,66.00,71.00,1,Canon
13,70.00,2,0,85.00,73.00,1,Ajay
14,70.00,0,1,67.00,73.00,1,Zar
15,67.00,1,1,64.00,75.00,1,Teja
16,80.00,0,1,68.00,77.00,1,Monu
17,67.00,0,1,66.00,78.00,1,Baba
18,89.00,0,1,78.00,80.00,1,Canon
19,90.00,0,1,90.00,89.00,1,Amir
20,87.00,0,1,88.00,85.00,1,Zar
21,68.00,0,1,80.00,97.00,1,Teja
22,69.00,0,1,78.00,80.00,1,Monu
23,80.00,0,1,84.00,80.00,1,Baba
24,80.00,1,1,76.00,80.00,1,Canon
25,80.00,1,1,88.00,84.00,1,Amin
26,87.00,0,1,85.00,85.00,1,Zar
27,75.00,0,2,80.00,90.00,1,Teja
28,90.00,0,3,70.00,75.00,1,Monu
29,88.00,0,3,85.00,92.00,1,Baba
30,70.00,0,1,70.00,87.00,1,Canon
...,...,...,...,...,...,...,...
341,81.00,2,2,66.00,79.00,1,Canon
342,68.00,1,4,71.00,71.00,1,Ajay
343,66.00,3,4,81.00,77.00,1,Zar
345,70.00,3,5,89.00,79.00,1,Monu
346,71.00,4,4,88.00,71.00,1,Baba
347,71.00,4,4,81.00,71.00,1,Canon
348,64.00,1,69,0.00,64.00,1,Ajay
349,60.00,3,65,0.00,61.00,1,Zar
351,61.00,6,0,60.00,60.00,0,Monu
352,62.00,5,0,62.00,63.00,0,Baba
353,63.00,4,0,63.00,65.00,0,Canon
354,64.00,3,0,65.00,69.00,0,Ajay
355,64.00,5,2,79.00,69.00,0,Zar
357,62.00,7,1,77.00,67.00,0,Monu
358,61.00,8,1,76.00,66.00,0,Baba
360,59.00,8,2,75.00,65.00,0,Ajay
361,62.55,1,2,72.00,79.00,1,Zar
362,72.87,0,3,80.30,85.50,1,Teja
363,75.90,0,4,80.00,85.00,1,Monu
364,59.00,4,2,71.00,69.00,0,Baba
365,82.50,3,4,87.00,83.00,1,Canon
366,59.37,3,1,65.00,71.00,0,Ajay
367,71.60,0,4,75.00,85.00,1,Zar
368,65.58,2,4,71.00,89.00,1,Teja
369,67.78,5,0,60.00,71.00,0,Monu
370,59.98,5,5,87.00,91.00,1,Baba
371,63.45,5,0,67.00,70.00,0,Canon
372,68.87,2,0,66.67,69.69,0,Ajay
373,80.48,0,3,79.00,88.89,1,Zar
375,100.00,5,3,88.00,88.00,1,Monu

In [6]:
len(df.drop_duplicates(subset=['Percentage','First_Round']))

301